version: 2

updates:
  - package-ecosystem: bun
    directory: "/web"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: gomod
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    target-branch: "main"
